language: php

matrix:
  include:
    - php: 7.3
      env: TESTS=1
    - php: 7.4
      env: COVERAGE=1
    - php: 8.0
      env: TESTS=1 PHPCS=1

before_script:
  - composer install --prefer-dist

script:
  - if [[ $TESTS ]]; then vendor/bin/phpunit; fi
  - if [[ $COVERAGE ]]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS ]]; then vendor/bin/phpcs --standard=PSR12 src/ tests/; fi

after_success:
  - if [[ $COVERAGE ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
